[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature